<CODE> -> <1> <LINE>|<1><CODE> <LINE>.
<LINE> -> <1> <ACTION> ';'|<1><IF>.
<IF> -> <1> 'if' <COND> '{' <LINE> '}' 'else' '{' <LINE> '}' |<1> 'if' <COND> '{' <CODE> '}'.
<COND> -> <1> '(' <OBS> ')' |<1> '(' <OBS> <OP> <OBS> ')' |<1> '(' '(' <AREXP> ')' <OP> '(' <AREXP> ')' ')'|<1>'('<COND> <LOGOP> <COND>')'.
<OBS> -> <1> 'count'<M>| <1> 'dist'<M>|<1>'p[' <Pidx> ']'<M>.
<OP> -> <1> '<'|<1> '>'|<1> '<='|<1>' >='.
<AREXP> -> <1> <OBS>|<1><V>|<1><AREXP> <AR> <AREXP>.
<AR> -> <1> '+'|<1> '*'|<1> '-'.
<V> -> <1> '0'|<1>'1'|<1>'2'|<1>'3'|<1>'4'|<1>'5'|<1>'6'|<1>'7'.
<LOGOP> -> <1> '||' |<1> '&&'.
<Pidx> -> <1> '0'|<1>'1'|<1>'2'|<1>'3'|<1>'4'|<1>'5'|<1>'6'|<1>'7'.
<M> -> <1> 'UP'|<1>'DOWN'|<1>'RIGHT'|<1>'LEFT'.
<ACTION> -> <1> '"UP"'|<1>'"DOWN"'|<1>'"RIGHT"'|<1>'"LEFT"'|<1>'"NEUTRAL"'.
