<OBS> -> <1>  'r_f_d' | <1>  'l_f_d' | <1>  'u_f_d' | <1>  'd_f_d'.
<OP> -> <1>  '<' | <1>  '>' | <1>  '<=' | <1>  '>='.
<AR> -> <1>  '+' | <1>  '*' | <1>  '-'.
<CODE> -> <1>  <LINE> | <1>  <CODE> <LINE>.
<ACTION> -> <1>  '"RIGHT"' | <1>  '"LEFT"' | <1>  '"UP"' | <1>  '"DOWN"' | <1>  '"NEUTRAL"'.
<V> -> <1>  '0' | <1>  '1' | <1>  '2' | <1>  '3' | <1>  '4' | <1>  '5' | <1>  '6' | <1>  '7'.
<AREXP> -> <1>  <OBS> | <1>  <V> | <1>  <AREXP> <AR> <AREXP>.
<LOGOP> -> <1>  '||' | <1>  '&&'.
<LINE> -> <1>  <ACTION> ';' | <1>  <IF>.
<IF> -> <1>  'if' <COND> '{' <LINE> '}' 'else' '{' <LINE> '}' | <1>  'if' <COND> '{' <LINE> '}'.
<COND> -> <1>  '(' <OBS> ')' | <1>  '(' <OBS> <OP> <OBS> ')' | <1>  '(' '(' <AREXP> ')' <OP> '(' <AREXP> ')' ')' | <1>  '(' 'l_f_d' ')' | <1>  '(' 'd_f_d' ')' | <2>  '(' 'u_f_d' ')'.
